# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9d9e212f8374078860d0f8833f0f038ae782f99900248e5d473d67e561659d118eb239bdf1ee120ae297061fb1a12c40c6bc16436628d3073e41d1ea512b4e9

test:
  secret_key_base: ad0b701c50a04e1f0e80fff7d1927e07d9be56bcf68adcc1420268821b5a3b67a8cde571229f1161087a0636d79a62e9c1c423d924a3f81833913ebbc556f53d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
